### ISSUE TITLE
NOVA Kernel Queston

### ISSUE THREAD

**Issue by lonnietc** [TUD-OS/NRE#49]
Hi All,

I am very happy that NRE will compile and build against NOVA.

NRE compiles and links against (updates within a few days):

https://github.com/TUD-OS/NOVA/tree/1ab3e588b8808146783772288f34905600dd21c2

but Udo has another NOVA repo that also seems to have updates (through 2021 within a few days) and the hypervisor compiles for x86_64 as well but will not compile against NRE:

https://github.com/udosteinberg/NOVA

I wanted to find out if there is a master NOVA branch somewhere that has all of these latest updates and fixes which will compile against NRE.

Once question that I have is as to which repo is the latest NOVA code since it seems that we have multiple NOVA branches floating about?

Any thoughts?

Cheers and have a great day.

**Comment by Nils-TUD** [comment]
There are indeed multiple versions. The ones I know of are:

1. https://github.com/udosteinberg/NOVA: maintained by Udo Steinberg, the original author of NOVA, at Bedrock Systems.
2. https://github.com/alex-ab/NOVA: maintained by Alexander Böttcher at Genode Labs.
3. [Hedron](https://github.com/cyberus-technology/hedron): a NOVA fork maintained by Julian Stecklina at Cyberus Technology.
4. https://github.com/TUD-OS/NOVA: the version NRE uses (not maintained).

At this point, NRE can only work with the NOVA repo in TUD-OS. I'm not sure how much the three others diverged, but I don't expect it to be a little tweak here and there, but really significant changes to adapt NRE to a new kernel ABI.

**Comment by lonnietc** [comment]
Absolutely agree as I have come across an number of different NOVA versions during my recent Internet researching and travels.

For now, I will just stay with what works with NRE so that I can focus on other components and look into the hypervisor upgrades in in the future if all goes well.

Thanks
