### ISSUE TITLE
Hardware Keyboard and Mouse Question

### ISSUE THREAD

**Issue by lonnietc** [TUD-OS/NRE#60]
Hi Nils,

Hope that all is well.

I was trying to look through to see if we had talked about this, but could not find any specific information.

By adding a small change to the "boot/vmmng" script 

#!tools/novaboot --iso=vmmtest.iso

I can have the "./b" which invokes nobaboot to build a small bootable iso.

I wanted to do this because in addition to testing via QEMU, I also want to test on some real hardware which is where the question comes in.

I am able to boot my generated ISO on either my AMD or Intel NUC 64-bit hosts but it turns out that the the keyboard and mouse do not work although it seems that the hypervisor is running.

What I am wondering is how I might be able to adjust either some NRE code, or possible some boot parameters for NOVA or NRE that will enable to keyboard and mouse to work on the hardware.  These devices are USB that I have on these systems as well.

I am not able to see any serial terminal when booting on hardware since I only have 1 monitor but wanted to see if you had any ideas on how to maybe proceed to get this working or to be able to collect some diagnostic data to help troubleshoot an effort to make it work.

Any thoughts or suggestions would be greatly appreciated.

Cheers and have a good weekend

**Comment by Nils-TUD** [comment]
NRE does not support USB devices, but only PS2 keyboard/mouse. Do you have legacy emulation enabled in the BIOS? In that case system management mode will emulate PS2 devices for them, so that it should work.

**Comment by lonnietc** [comment]
Thanks for getting back to me on this and I will give it a try.

I am also now wondering what it might take to get NRE to support USB devices as well since that is something definitely needed going forward too.

Does your time look like it is freeing up any?  (I'm always hopeful give the challenges that are faced)

Cheers

**Comment by Nils-TUD** [comment]
> Does your time look like it is freeing up any? (I'm always hopeful give the challenges that are faced)

No, sorry. In general, the chances that I have the time and motivation to continue the development of NRE are tiny. So, better don't plan with that ;)

**Comment by lonnietc** [comment]
Just an update on this.

I tried legacy emulation enabled in the BIOS but that did not work either.

**Comment by Nils-TUD** [comment]
Ok, then I don't know from the top of my head what that could be. You could try to debug the keyboard component by adding more prints to see what's happening. So, for example, is the initial setup working? Are interrupts arriving? Are any key presses detected?

**Comment by lonnietc** [comment]
Thanks, I'll keep digging into it more to see what I can find.

Appreciate all of the help and guidance that you have given me on this journey so far, my friend.
