### ISSUE TITLE
Munich and Mini Guests

### ISSUE THREAD

**Issue by lonnietc** [TUD-OS/NRE#61]
Hi Nils,

I am exploring Munich and Mini guest apps in NRE.

1. If I understand correctly, munich is used as a loader to start up Linux (i.e. Tinycore, etc.), correct?

2. Now the question is really about the "mini" guest. It seems to be using "vancouver" (libseoul) but when looking at the code, it also seems to be a type of bare metal implementation.  It does not seems to rely on the libseoul or NRE headers and looks to be self-contained.  Can you please tell me more about this one?

cheers and have a good weekend

**Comment by Nils-TUD** [comment]
> 1. If I understand correctly, munich is used as a loader to start up Linux (i.e. Tinycore, etc.), correct?

Yes.

> 2. Now the question is really about the "mini" guest. It seems to be using "vancouver" (libseoul) but when looking at the code, it also seems to be a type of bare metal implementation.  It does not seems to rely on the libseoul or NRE headers and looks to be self-contained.  Can you please tell me more about this one?

It's a mini kernel that just serves as a test for Seoul by being a simple guest "OS" that runs inside the VM provided by Seoul. Therefore it "uses" Seoul in the same sense as Tinycore Linux is using it.

**Comment by lonnietc** [comment]
Thanks Nils.

That's about what I was thinking as my use of the term "Bare Metal" was meaning within Seoul.
